name: Update gist with WakaTime stats
on:
  watch:
    types: [started]
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 829c42f3dd17f85fc8e8f06f1e6bc4c9
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
